---
version: '3.7'

services:

  test: &base
    build:
      context: .
      target: base
    working_dir: /app
    entrypoint:
      - yarn
      - run
      - test

  sh:
    <<: *base
    volumes:
      - ".:/app"
      - /app/node_modules
      - "$HOME/.aws:/root/.aws"
    entrypoint:
      - "bash"

  trivy:
    image: aquasec/trivy:0.10.2
    working_dir: /app
    volumes:
      - ".:/app"
      - "./cache:/root/.cache/"
      - "/var/run/docker.sock:/var/run/docker.sock"

  ctpl:
    image: ikerry/cptl:latest
    working_dir: /app
    volumes:
      - ".:/app"
      - "$HOME/.aws:/root/.aws"
