---
version: '3.7'

services:

  x-default: &base
    build:
      context: .
      target: dev
    working_dir: /app
    platform: linux/amd64
    volumes:
      - "$HOME/.aws:/root/.aws"
      - /app/node_modules
      - ".:/app"

  test:
    build:
      context: .
      target: dev
    working_dir: /app
    platform: linux/amd64
    volumes:
      - "$HOME/.aws:/root/.aws"
      - /app/node_modules
      - ".:/app"
    entrypoint:
      - yarn
      - run
      - test

  sh:
    <<: *base
    entrypoint:
      - "bash"

  ctpl:
    working_dir: /app
    image: ikerry/cptl:latest
    volumes:
      - ".:/app"
      - "$HOME/.aws:/root/.aws"
