---
version: '3.2'

services:

  test: &base
    build:
      context: .
      dockerfile: Dockerfile-dev
    working_dir: /app
    entrypoint:
      - yarn
      - run
      - test

  sh:
    <<: *base
    volumes:
      - ".:/app"
      - /app/node_modules
      - "$HOME/.aws:/root/.aws"
    entrypoint:
      - "bash"

  ctpl:
    image: ikerry/cptl:v0.1.4
    working_dir: /app
    volumes:
      - ".:/app"
      - "$HOME/.aws:/root/.aws"
