version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  ut:
    machine: true
    steps:
      - checkout
      - run:
          name: Unit Test
          command: |
            make test

workflows:
  untagged-build:
    jobs:
      - ut
