version: 2.1
jobs:
  ut:
    machine: true
    docker:
      - image: ikerry/ctpl:v1.1.0
    steps:
      - checkout
      - run:
          name: Unit Test
          command: |
            yarn run test

workflows:
  version: 2
  untagged-build:
    jobs:
      - ut
